### ISSUE TITLE
Cannot Initialize Astrum

### ISSUE THREAD

**Issue by philbert440** [NoDivide/astrum#112]
#### Tell us about the issue you are experiencing
philip@CortanaDev1:~/pattern-library$ sudo astrum init ./
/usr/local/lib/node_modules/astrum/manager/utils.js:41
                throw(new Error(chalk.red('Pattern library has already been initialized.')));
                ^

Error: Pattern library has already been initialized.
    at /usr/local/lib/node_modules/astrum/manager/utils.js:41:23
    at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
philip@CortanaDev1:~/pattern-library$ ls
astrum-config.json
philip@CortanaDev1:~/pattern-library$ astrum update
/usr/local/lib/node_modules/astrum/manager/utils.js:24
            throw(new Error(chalk.red("No astrum-config.json file found in project root.")));
            ^

Error: No astrum-config.json file found in project root.
    at Object.module.exports.init (/usr/local/lib/node_modules/astrum/manager/utils.js:24:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/astrum/manager/astrum-update.js:9:7)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
philip@CortanaDev1:~/pattern-library$ nodejs --version
v7.7.3
philip@CortanaDev1:~/pattern-library$ npm -v
3.3.6
philip@CortanaDev1:~/pattern-library$ astrum -V
1.9.3

#### What behaviour would you expect?
Init just creates an empty astrum-config file and throws the already initialized error. Tried all different variations and ruled out path / permissions issues.

#### How can this issue be replicated?
Clean install on Ubuntu 14 server.

#### Your environment

Platform: Linux
OS Version: Ubuntu 14.04
Node Version: 7.7.3
NPM Version: 3.3.6
Astrum Version: 1.9.3

**Comment by philbert440** [comment]
Nvm got it working, I guess it didn't need to initialize to start working  \(. .)/
