### ISSUE TITLE
Getting EACCES: permission denied when trying to init

### ISSUE THREAD

**Issue by ultraloveninja** [NoDivide/astrum#172]
#### Tell us about the issue you are experiencing
When I try to run `astrum init /pattern-library` within the folder that I am trying use, I get this error:

```
Error: Error: EACCES: permission denied, mkdir '/pattern-library'
Error: Error: EACCES: permission denied, mkdir '/pattern-library'
/usr/local/lib/node_modules/astrum/manager/utils.js:31
            throw(new Error(chalk.red("No data.json file found in " + _this.$config.path )));
            ^

Error: No data.json file found in /pattern-library
    at Object.init (/usr/local/lib/node_modules/astrum/manager/utils.js:31:19)
    at /usr/local/lib/node_modules/astrum/manager/utils.js:58:27
    at doneOne (/usr/local/lib/node_modules/astrum/node_modules/fs-extra/lib/copy/ncp.js:237:23)
    at onError (/usr/local/lib/node_modules/astrum/node_modules/fs-extra/lib/copy/ncp.js:229:12)
    at /usr/local/lib/node_modules/astrum/node_modules/fs-extra/lib/copy/ncp.js:147:23
    at FSReqCallback.oncomplete (fs.js:148:20)
```

#### What behaviour would you expect?
Was hoping it would run as expected..?

#### Your environment

Platform: MacOS
OS Version: Mojave
Node Version: 11.1.0
NPM Version: 6.4.1
Astrum Version: 1.9.5

**Comment by ultraloveninja** [comment]
Actually, disregard. Looks like there was something messed up on my end with my directory structure.
