### ISSUE TITLE
Error thrown when trying to init Astrum in the current folder or a folder that already exists.

### ISSUE THREAD

**Issue by ZakkMan** [NoDivide/astrum#23]
#### Tell us about the issue you are experiencing

If I create the folder with `mkdir pattern-library` then run `astrum init pattern-library` or try to run `astrum init .` I get the following error:

```
/usr/local/lib/node_modules/astrum/manager/utils.js:41
                throw(new Error(chalk.red('Pattern library has already been initialized.')));
                ^

Error: Pattern library has already been initialized.
    at /usr/local/lib/node_modules/astrum/manager/utils.js:41:23
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)

```
#### What behaviour would you expect?

I would have expected that the cli would initialize Astrum within the folder if it already exists or that it would be possible to initialize Astrum in the current directory.
#### How can this issue be replicated?
1. Make a folder:
   `$ mkdir projects/pattern-library`
2. run `astrum init`:
   `$ astrum init projects/pattern-library`
#### Your environment

Platform: Mac
OS Version: OS X Yosemite (10.10.5)
Node Version: v4.2.6
NPM Version: v3.5.3
Astrum Version: Current version

**Comment by matt-west** [comment]
@RyanHavoc Could you please take a look at this one when you get chance.

**Comment by RyanHavoc** [comment]
@ZakkMan I'm going to mark this as a feature request. I'll need to add in some detection to have Astrum install into a pre-existing folder. The thought process was that Astrum would be installed into a "clean" folder so that no existing files could be overwritten when Astrum is installed/updated. I'll need to add a check to ensure the folder is empty when you run `astrum init` to initialise into the folder you're in or `astrum init ./existing-folder` to initialise into a folder you've created before hand.

I've added this to the feature request list: [https://github.com/NoDivide/astrum/wiki/Project-Roadmap](https://github.com/NoDivide/astrum/wiki/Project-Roadmap)

**Comment by RyanHavoc** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kzOCjTcD&#x2F;13-add-facility-to-initialise-astrum-into-a-pre-existing-folder"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add facility to initialise Astrum into a pre-existing folder.</a>

**Comment by philipbelesky** [comment]
Hey, loving the library. Not sure if this use case belongs with this issue as an implementation detail or should be added as a separate feature request issue (let me know if so and I'll add one).

My use case is for distributing an npm/bower package with astrum as a dev dependency but without *without* bundling/packaging the core pages generated when creating an astrum project — ie the `index.html` and `app/` files that were auto-generated and that I've no need to modify. The package *would* include the `/components`, `data.json`, etc that are project-specific.

It would be great if when running `astrum init folder` the init process would skip over the files it would create in `folder` it they already exist; or that it could be run with a flag that allows it to do so optionally.

Would you be interested in a pull request that implements this along with the original behaviour? I should be able to give it a shot.

**Comment by RyanHavoc** [comment]
@philipbelesky Could you create a new issue to discuss this on please.
