### ISSUE TITLE
Can't create a new component

### ISSUE THREAD

**Issue by MrSunshyne** [NoDivide/astrum#4]
I tried creating a new component with the example command.

I get this error 

```
x@y [~/LSL/astrum/press] $ astrum new buttons/default
/usr/local/lib/node_modules/astrum/manager/utils.js:160
        return this.$data.groups.findIndex(function(item) {
                                 ^
TypeError: undefined is not a function
    at Object.module.exports.getGroupIndex (/usr/local/lib/node_modules/astrum/manager/utils.js:160:34)
    at Object.module.exports.componentExists (/usr/local/lib/node_modules/astrum/manager/utils.js:354:32)
    at Object.module.exports.validateComponent (/usr/local/lib/node_modules/astrum/manager/utils.js:343:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/astrum/manager/astrum-new.js:38:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

not sure what's up

I installed using npm -g as usual.

**Comment by matt-west** [comment]
Hi @MrSunshyne,

Which node version are you running?
`node -v`

**Comment by RyanHavoc** [comment]
@MrSunshyne We're going to assume you've resolved this issue by upgrading your npm and it can be closed. If you're still having issues do let us know and we'll re-open.
