### ISSUE TITLE
Cannot add components: undefined is not a function

### ISSUE THREAD

**Issue by brtdesign** [NoDivide/astrum#60]
#### Tell us about the issue you are experiencing
running:

```D:\src\app>astrum new buttons/default```

gives:

```
C:\Users\bent\AppData\Roaming\npm\node_modules\astrum\manager\utils.js:174
        return this.$data.groups.findIndex(function(item) {
                                 ^
TypeError: undefined is not a function
    at Object.module.exports.getGroupIndex (C:\Users\bent\AppData\Roaming\npm\node_modules\astrum\manager\utils.js:174:34)
    at Object.module.exports.componentExists (C:\Users\bent\AppData\Roaming\npm\node_modules\astrum\manager\utils.js:374:32)
    at Object.module.exports.validateComponent (C:\Users\bent\AppData\Roaming\npm\node_modules\astrum\manager\utils.js:363:18)
    at Object.<anonymous> (C:\Users\bent\AppData\Roaming\npm\node_modules\astrum\manager\astrum-new.js:38:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

#### What behaviour would you expect?
New component created

#### How can this issue be replicated?
Running: ```D:\src\app>astrum new */*``` 
#### Screenshots / Screencast
-
#### Your environment

Platform: Windows 10 Pro
OS Version:  1511
Node Version: 0.12.2
NPM Version: 2.7.4
Astrum Version: 1.6.2

---

*Added: This is a brand new install of astrum

Thanks!

**Comment by RyanHavoc** [comment]
@brtdesign You need to update your version of Node/NPM.
