### ISSUE TITLE
Updating from 1.5.15 fails

### ISSUE THREAD

**Issue by bitstarr** [NoDivide/astrum#82]
I wanted to update my style guide from astrum 1.5.15 to the current version. I globally updated astrum successfully. In the project it failed by using `astrum update`.

```
/home/dev/node-v5.10.1-linux-x64/lib/node_modules/astrum/manager/utils.js:24
            throw(new Error(chalk.red("No astrum-config.json file found in project root.")));
            ^

Error: No astrum-config.json file found in project root.
    at Object.module.exports.init (/home/dev/node-v5.10.1-linux-x64/lib/node_modules/astrum/manager/utils.js:24:19)
    at Object.<anonymous> (/home/dev/node-v5.10.1-linux-x64/lib/node_modules/astrum/manager/astrum-update.js:9:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

Platform: Debian
OS Version: Stable
Node Version: 5.10.1
NPM Version: 3.8.3
Astrum Version: 1.5.15 / 1.8.1

**Comment by matt-west** [comment]
Hi @bitstarr, Are you running this command from the same directory as your `astrum-config.json` is located in?

**Comment by bitstarr** [comment]
I am runnig this command where the data.json, index.html and the app folder is.

**Comment by matt-west** [comment]
@bitstarr Try running the update command from the same folder that contains the `astrum-config.json` file.

**Comment by bitstarr** [comment]
Well there no such file. Did you change the file names over the version? Is it even possible to update from 1.5.15?

**Comment by RyanHavoc** [comment]
@bitstarr No there shouldn't be any issues updating from 1.5.15. If you astrum-config.json file is missing you'll need to create a new one manually the contents are:

````
{
    "path": "./path/to/your/library"
}
````
See if that works.

**Comment by matt-west** [comment]
Closing due to inactivity.
